version: '2.2'
services:
  unificontroler:
    build:
      context: .
    ports:
      - "3478:3478/udp"
      - "6789:6789/tcp"
      - "8080:8080/tcp"
      - "8443:8443/tcp"
      - "8843:8843/tcp"
      - "8880:8880/tcp"
      - "8881:8881/tcp"
      - "8882:8882/tcp"
    environment:
      UNIFI_MONGO_DB_HOST: "mongo"
      UNIFI_MONGO_DB_USE_AUTH: "FALSE"
      UNIFI_MONGO_DB_USER: ""
      UNIFI_MONGO_DB_PASS: ""
      UNIFI_MONGO_DB_NAME: "ace"
      UNIFI_MONGO_DB_STAT_NAME: "ace-stat"
      UNIFI_MONGO_DB_PORT: "27017"
      UNIFI_MONGO_DB_WAIT_TIMEOUT: "60"
    depends_on:
      - mongo
    volumes:
      - unifi_data:/var/lib/unifi

  mongo:
    image: mongo
    volumes:
      - unifi_mongo_data:/data/db
volumes:
  unifi_data:
  unifi_mongo_data: